repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: pretty-format-json
      args: [--autofix, --no-ensure-ascii, --no-sort-keys]
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.1
    hooks:
      # Run the linter.
      - id: ruff
        # types_or: [ python, pyi ]
        # args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        # types_or: [ python, pyi, jupyter ]
